name: Deliver

on:
  push:
    tags:
      - 3.*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy new artefact
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Git
        run: git config --global user.email "ci@github.com" && git config --global user.name "Github CI"
      - name: Setup Java 8 and Maven
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          server-id: 'github'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_TOKEN
      - run: mvn --batch-mode versions:set -DnewVersion=$(echo ${{github.ref}}|cut -d'/' -f 3)
      - name: Deliver to Github Maven Repo
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: 'Paylib-Services'
          MAVEN_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: mvn --batch-mode versions:set -DnextSnapshot=true
      - run: git add pom.xml && git commit -m 'Prepare next release' && git push origin HEAD:master
